parameters:
  settings.automation.mode: '%env(AUTOMATION_MODE)%'
  settings.automation.entities: '%env(json:AUTOMATION_ENTITIES)%'
  settings.automation.external_control_url: '%env(AUTOMATION_EXTERNAL_CONTROL_URL)%'